### ISSUE TITLE
Browser testing

### ISSUE THREAD

**Issue by joeldrapper** [SpectreThemes/Focus#1]
## Desktop Browsers

- [x] Google Chrome
- [x] Firefox
- [x] Safari
- [x] Internet Explorer / Edge

## Android

- [ ] Opera Mini
- [ ] Google Chrome
- [ ] Firefox

## iOS

- [ ] Google Chrome
- [ ] Safari

**Comment by taiyab** [comment]
iPhone - Safari (14:00 - 2 Nov 2015)

![image](https://cloud.githubusercontent.com/assets/5337876/10883502/56b4d7d6-816a-11e5-807f-75439c66b69e.png)

![image](https://cloud.githubusercontent.com/assets/5337876/10883505/5efac996-816a-11e5-8800-72b799db6651.png)

![image](https://cloud.githubusercontent.com/assets/5337876/10883522/75e4f23a-816a-11e5-8df2-0347cb45cb1b.png)

![image](https://cloud.githubusercontent.com/assets/5337876/10883525/7a25d29c-816a-11e5-9840-dcad99f5a92c.png)

![image](https://cloud.githubusercontent.com/assets/5337876/10883528/7e8af394-816a-11e5-8e27-027e934e2eb2.png)

![image](https://cloud.githubusercontent.com/assets/5337876/10883530/82040dda-816a-11e5-8371-c8f7ac3b60f0.png)

![image](https://cloud.githubusercontent.com/assets/5337876/10883531/85664c54-816a-11e5-8532-18d273b7d2f7.png)

![image](https://cloud.githubusercontent.com/assets/5337876/10883533/887d6436-816a-11e5-9add-bf3191f2d67f.png)

![image](https://cloud.githubusercontent.com/assets/5337876/10883534/8cec32e0-816a-11e5-973e-f732025f2625.png)

![image](https://cloud.githubusercontent.com/assets/5337876/10883539/908a00bc-816a-11e5-97bd-a51181e7f852.png)

![image](https://cloud.githubusercontent.com/assets/5337876/10883542/947344c2-816a-11e5-964e-3e47a0f7dc80.png)

**Comment by joeldrapper** [comment]
@taiyab I deleted your comment with those screenshots as so much has changed since you took those. When we review everything this evening, lets grab some more screenshots of any mobile issues still outstanding and make a new issue for each of them,

**Comment by joeldrapper** [comment]
This discussion is now being managed in Basecamp.
