### ISSUE TITLE
Post Title Legibility

### ISSUE THREAD

**Issue by taiyab** [SpectreThemes/Focus#6]
We need to do something about the legibility of text on images on mobile. The gradient from the bottom doesn't help clarify the text on mobile devices.

I can see two options:
- Replacing the gradient with top to middle
- Darkening whole BG image (black overlay, 30-40% alpha)

@joeldrapper Thoughts?

**Comment by joeldrapper** [comment]
- [ ] Add a very subtle shadow to headings inside the hero object
- [ ] Darken the `vignette`
