### ISSUE TITLE
Remove https / http from author URL

### ISSUE THREAD

**Issue by taiyab** [SpectreThemes/focus#8]
Remove https/http from author URL when displayed.

![image](https://cloud.githubusercontent.com/assets/5337876/10977278/fb9a21aa-83e7-11e5-866b-b1325de49a4b.png)

**Comment by joeldrapper** [comment]
It a shame there isn't a nice way to do this. Going to have to use jQuery I think :disappointed:

**Comment by taiyab** [comment]
@joeldrapper As long as it doesn't harm performance too much.

**Comment by joeldrapper** [comment]
@taiyab it's not too bad. This script will run after the rest of the page has been rendered.
